const IMPORT_MAP = {
  'imports': {
    'yjs':'/deps/yjs/src/index.js',
    'y-prosemirror':'/deps/y-prosemirror/src/y-prosemirror.js',
    'y-protocols/sync':'/deps/y-protocols/sync.js',
    'y-protocols/auth':'/deps/y-protocols/auth.js',
    'y-protocols/awareness':'/deps/y-protocols/awareness.js',
    'y-websocket':'/deps/y-websocket/src/y-websocket.js',
    'lib0':'/deps/lib0/index.js',
    'lib0/observable':'/deps/lib0/observable.js',
    'lib0/array':'/deps/lib0/array.js',
    'lib0/math':'/deps/lib0/math.js',
    'lib0/map':'/deps/lib0/map.js',
    'lib0/url':'/deps/lib0/url.js',
    'lib0/diff':'/deps/lib0/diff.js',
    'lib0/environment':'/deps/lib0/environment.js',
    'lib0/dom':'/deps/lib0/dom.js',
    'lib0/eventloop':'/deps/lib0/eventloop.js',
    'lib0/encoding':'/deps/lib0/encoding.js',
    'lib0/decoding':'/deps/lib0/decoding.js',
    'lib0/random':'/deps/lib0/random.js',
    'lib0/promise':'/deps/lib0/promise.js',
    'lib0/buffer':'/deps/lib0/buffer.js',
    'lib0/error':'/deps/lib0/error.js',
    'lib0/binary':'/deps/lib0/binary.js',
    'lib0/function':'/deps/lib0/function.js',
    'lib0/set':'/deps/lib0/set.js',
    'lib0/logging':'/deps/lib0/logging.js',
    'lib0/time':'/deps/lib0/time.js',
    'lib0/string':'/deps/lib0/string.js',
    'lib0/iterator':'/deps/lib0/iterator.js',
    'lib0/object':'/deps/lib0/object.js',
    'lib0/webcrypto':'/deps/lib0/webcrypto.js',
    'lib0/websocket':'/deps/lib0/websocket.js',
    'lib0/broadcastchannel':'/deps/lib0/broadcastchannel.js',
    'lib0/mutex':'/deps/lib0/mutex.js',
    'prosemirror-state': '/deps/prosemirror-state/dist/index.js',
    'prosemirror-view': '/deps/prosemirror-view/dist/index.js',
    'prosemirror-model': '/deps/prosemirror-model/dist/index.js',
    'prosemirror-schema-basic': '/deps/prosemirror-schema-basic/dist/index.js',
    'prosemirror-schema-list': '/deps/prosemirror-schema-list/dist/index.js',
    'prosemirror-transform': '/deps/prosemirror-transform/dist/index.js',
    'prosemirror-example-setup': '/deps/prosemirror-example-setup/dist/index.js',
    'prosemirror-history': '/deps/prosemirror-history/dist/index.js',
    'prosemirror-commands': '/deps/prosemirror-commands/dist/index.js',
    'prosemirror-dropcursor': '/deps/prosemirror-dropcursor/dist/index.js',
    'prosemirror-gapcursor': '/deps/prosemirror-gapcursor/dist/index.js',
    'prosemirror-menu': '/deps/prosemirror-menu/dist/index.js',
    'prosemirror-inputrules': '/deps/prosemirror-inputrules/dist/index.js',
    'prosemirror-keymap': '/deps/prosemirror-keymap/dist/index.js',
    'prosemirror-tables': '/deps/prosemirror-tables/dist/index.js',
    'rope-sequence': '/deps/rope-sequence/dist/index.es.js',
    'w3c-keyname': '/deps/w3c-keyname/index.es.js',
    'orderedmap': '/deps/orderedmap/dist/index.js',
    'crelt': '/deps/crelt/index.es.js',
    '@lit/task': '/deps/lit/task/task.js',
    '@lit/reactive-element': '/deps/lit/reactive-element/reactive-element.js',
  },
};

(function setImportMap() {
  const script = document.createElement('script');
  script.setAttribute('type', 'importmap');
  const map = JSON.stringify(IMPORT_MAP);
  script.textContent = map;
  document.head.append(script);
}());
