name: Dark Alley release email

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  action:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Use email bot
        uses: adobecom/da-email-bot@main
        env:
          SG_TO_EMAIL: ${{ secrets.SG_TO_EMAIL }}
          SG_FROM_EMAIL: ${{ secrets.SG_FROM_EMAIL }}
          SG_FROM_NAME: ${{ secrets.SG_FROM_NAME }}
          SG_KEY: ${{ secrets.SG_KEY }}
          SG_TEMPLATE: 'd-24723d9fc5964674a61426db17553c58'
